FROM node:16-alpine

WORKDIR /app

COPY frontend/package.json ./

# Install dependencies
RUN npm install

# Copy all frontend files
COPY frontend/ ./

# TypeScript type checking
RUN npm run tsc

EXPOSE 3000

CMD ["npm", "start"]