FROM node:16-alpine

WORKDIR /app

COPY frontend/package.json ./

# Install dependencies
RUN npm install

# We don't copy the frontend files here as we'll mount them as a volume
# to enable hot reloading

EXPOSE 3000

# Start with react-scripts' development server which includes hot reloading
CMD ["npm", "start"]